export const types = {
  UPDATE_STAFF_DATA: 'UPDATE_STAFF_DATA',
  UPDATE_SLIDEBAR_DATA: 'UPDATE_SIDEBAR_DATA',
  UPDATE_INTRODUCTION_DATA: 'UPDATE_INTRODUCTION_DATA',
  UPDATE_STAFF_TYPE: 'UPDATE_STAFF_TYPE',
  UPDATE_NEWS_DATA: 'UPDATE_NEWS_DATA'
}
