export const types = {
  UPDATE_STAFF_DATA: 'UPDATE_STAFF_DATA',
  UPDATE_SLIDEBAR_DATA: 'UPDATE_SIDEBAR_DATA',
  UPDATE_INTRODUCTION_DATA: 'UPDATE_INTRODUCTION_DATA',
  UPDATE_STAFF_TYPE: 'UPDATE_STAFF_TYPE',
  UPDATE_NEWS_DATA: 'UPDATE_NEWS_DATA',
  UPDATE_VIDEO_DATA: 'UPDATE_VIDEO_DATA',
  UPDATE_NAVIGATION_DATA: 'UPDATE_NAVIGATION_DATA',
  UPDATE_CONTENT_DATA: 'UPDATE_CONTENT_DATA',
  UPDATE_ALBUM_DATA: 'UPDATE_ALBUM_DATA',
  UPDATE_BANNER_DATA: 'UPDATE_BANNER_DATA',
  UPDATE_TEACHING_EXCELLENCE_DATA: 'UPDATE_TEACHING_EXCELLENCE_DATA'
}
